[versions]
accompanistVersion = "0.37.3"
agp = "8.10.1"
appcompatVersion = "1.7.1"
coilComposeVersion = "2.7.0"
composePersianDatePickerVersion = "1.1.1"
constraintlayoutVersion = "2.2.1"
kotlin = "2.1.20"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.9.1"
activityCompose = "1.10.1"
jtds = "1.3.1"
composeBom = "2025.06.01"
materialVersion = "1.12.0"
hiltAndroidCompiler = "2.51.1"
hiltCompiler = "1.2.0"
hiltNavigationCompose = "1.2.0"
materialIconsExtended = "1.7.8"
kotlinxSerializationJsonVersion = "1.9.0"
navigationCompose = "2.9.1"
pagingComposeVersion = "3.2.1"
pagingRuntimeKtxVersion = "3.3.6"
persiandateVersion = "1.7.1"
persianrangedatepickerVersion = "1.3.1"
roomKtx = "2.7.2"
dagger-hilt = "2.51.1"
google-devtools-ksp = "2.1.20-1.0.32"
roomPagingVersion = "2.7.2"
roomRuntime = "2.7.2"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityCompose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingComposeVersion" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtxVersion" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "roomPagingVersion" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilComposeVersion" }
compose-persian-date-picker = { module = "com.github.razaghimahdi:Compose-Persian-Date-Picker", version.ref = "composePersianDatePickerVersion" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJsonVersion" }
jtds = { module = "net.sourceforge.jtds:jtds", version.ref = "jtds" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompiler" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomKtx" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroidCompiler" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
material = { module = "com.google.android.material:material", version.ref = "materialVersion" }
persiandate = { module = "com.github.samanzamani:PersianDate", version.ref = "persiandateVersion" }
persianrangedatepicker = { module = "com.github.ali-sardari:PersianRangeDatePicker", version.ref = "persianrangedatepickerVersion" }

[plugins]
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "google-devtools-ksp" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }